### ISSUE TITLE
error in tr_ID.txt

### ISSUE THREAD

**Issue by sun9700** [cvjena/costarica-moths#2] opened 2017-04-26 14:00 UTC
there are 990 1s in tr_ID.txt, num of train: 990, num of test: 1320
please update update train samples to 1732, thanks!

**Comment by MarcelSimon** [comment] 2017-04-26 14:09
Duplicate of #1 

I'm working on this issue and the update will come soon

**Closed as completed by MarcelSimon** 2017-04-26 14:09 UTC

**Comment by sun9700** [comment] 2017-04-27 03:15
Sorry for the duplication. Thanks for your effort!

**Comment by sun9700** [comment] 2017-06-07 04:51
@MarcelSimon is there any news? What about release the ground-truth without train/test split?
